name: Deploy to Github Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: uv sync
      
      - name: Deploy GH Pages
        run: uv run mkdocs gh-deploy --force
